# Generated by Django 5.1.4 on 2024-12-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20, unique=True)),
                ('signal', models.CharField(choices=[('Buy', 'Al'), ('Sell', 'Sat'), ('Hold', 'Bekle')], max_length=4)),
                ('timeframe', models.CharField(choices=[('Short', 'Kısa Vade'), ('Medium', 'Orta Vade'), ('Long', 'Uzun Vade')], max_length=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
