# Generated by Django 5.1.4 on 2025-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_customuser_options_customuser_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='package',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('basic', 'Temel'), ('pro', 'Profesyonel'), ('premium', 'Premium')], default='free', max_length=10, verbose_name='Paket'),
        ),
    ]
