# Generated by Django 5.1.4 on 2024-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_premium',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='price_at_signal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pair',
            field=models.CharField(max_length=20),
        ),
    ]
