# Generated by Django 5.1.4 on 2025-01-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_alter_customuser_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='package',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('premium', 'Premium')], default='free', max_length=10, verbose_name='Paket'),
        ),
    ]
